### ISSUE TITLE
URGENT! Account linking not working as expected

### ISSUE THREAD

**Issue by originalgish** [mrmerkone/botislav-bot#1]
I've added [my opendota profile](https://www.opendota.com/players/91247415) to this AWESOME botislav dude, but when I ask for the last match it throws me one I did not participate in. Like this "Ты выйграл на Mirana со счетом 7/1/20 https://www.opendota.com/matches/6862778480".

Investigate and fix PLS

**Comment by mrmerkone** [comment]
Fixed in [d3fc10d](https://github.com/mrmerkone/botislav-bot/commit/d3fc10db30c6f29e46075b4891c2a4cfd276c9c9)

you can now tell bot what opendota account add to your context

example: 

`привяжи https://www.opendota.com/players/91247415`
